export const REGEX_URL_SLISM = new RegExp(
  '^https://calorie.slism.jp/[0-9]{6}/?'
)
export const NUTRIENT_DICTIONARY = {
  calorie: 'エネルギー',
  protein: 'タンパク質',
  fat: '脂質',
  carbohydrate: '炭水化物',
  sugariness: '糖質',
  dietaryFiber: '食物繊維',
  salt: '食塩相当量',
  vitaminA: 'ビタミンA',
  vitaminB1: 'ビタミンB1',
  vitaminB2: 'ビタミンB2',
  niacin: 'ナイアシン',
  vitaminB6: 'ビタミンB6',
  vitaminC: 'ビタミンC',
  vitaminD: 'ビタミンD',
  vitaminE: 'ビタミンE',
  folicAcid: '葉酸',
  pantothenicAcid: 'パントテン酸',
  biotin: 'ビオチン',
  sodium: 'ナトリウム',
  potassium: 'カリウム',
  calcium: 'カルシウム',
  magnesium: 'マグネシウム',
  phosphorous: 'リン',
  iron: '鉄',
  zinc: '亜鉛',
  copper: '銅',
  manganese: 'マンガン',
  selenium: 'セレン',
  chromium: 'クロム',
  molybdenum: 'モリブデン',
  iodine: 'ヨウ素',
}
